name: test

on:
  workflow_dispatch: # Enables the manual trigger button
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run CI Setup Action
        id: ci-step
        uses: ./.github/actions/ci-setup
      
