name: test

on:
  workflow_dispatch: # Enables the manual trigger button

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: clone 
        uses: actions/checkout@v4
      - name: build
        run: echo "build"
      
