name: Manual Workflow

on:
  workflow_dispatch: # Enables the manual trigger button
  schedule:
    - cron: '10 15 * * *'  

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
