name: 2nd workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  checkout:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "build"
    needs: checkout
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
    needs: build
    strategy:
      matrix:
        node-version: [10, 11, 12]
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "deploy"
    needs: test
