name: dummy
on:
  workflow_dispatch:
  
jobs:

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checout code
        uses: actions/checkout@v4
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "build"

      - name: composite
        uses: ./.github/actions/setup-environment
    needs: checkout
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
    needs: build

  deploy:
    environment:
      name: Prod
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "test"
    needs: test
