name: dummy
on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "RESULT=10" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "The result is $RESULT"
    needs: test
